export const strings = {
  loginText: "Login",
  signInYourAccount: "Sign in to your account",
  emailLabel: "Email",
  emailPlaceholder: "Enter your email",
  passwordLabel: "Password",
  passwordPlaceholder: "Enter your password",
  forgotPassword: "Forgot Password?",
  noAccountText: "Don't have an account? ",
  signUpLink: "Sign up",
  welcomeLogoText: "MetaEstetics",
  welcomeTitle: "Welcome",
  welcomeSubtitle: "Your journey to better aesthetics starts here",
  welcomeSignUpButton: "Sign Up",
  createAccountTitle: "Create Account",
  createAccountDescription: "Enter your email and password to create your account.",
  confirmPasswordLabel: "Confirm Password",
  confirmPasswordPlaceholder: "Confirm your password",
  nextButton: "Next",
  personalInformationTitle: "Personal Information",
  personalInformationDescription: "Please provide your personal details.",
  firstNameLabel: "First Name",
  firstNamePlaceholder: "Enter your first name",
  lastNameLabel: "Last Name",
  lastNamePlaceholder: "Enter your last name",
  phoneNumberLabel: "Phone Number",
  dateOfBirthLabel: "Date of Birth",
  dateOfBirthPlaceholder: "Select your date of birth",
  genderLabel: "Gender",
  genderPlaceholder: "Select your gender",
  previousButton: "Previous",
  uploadProfilePhotoTitle: "Upload Profile Photo (Optional)",
  uploadProfilePhotoDescription: "You can add a profile photo to personalize your account.",
  reviewInformationTitle: "Review Your Information",
  submittingButton: "Submitting...",
  submitButton: "Submit",
  contactInformationTitle: "Contact Information",
  phoneLabel: "Phone:",
  editProfileButton: "Edit Profile",
  viewClinicsButton: "View Clinics",
  settingsButton: "Settings",
  logoutButton: "Logout",
  userDataNotAvailable: "User data not available.",
  errorAlertTitle: "Error",
  profileUpdateSuccessMessage: "Profile updated successfully!",
  successAlertTitle: "Success",
  cancelButton: "Cancel",
  saveChangesButton: "Save Changes",
};